/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/ferrari-model/source/ferrari.glb -t 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'


export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/ferrari.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.956, 0.313, 1.161]} rotation={[Math.PI / 2, 0, 0]} scale={[-1.04, 1.04, 1.04]}>
        <mesh geometry={nodes.LOD_A_TYRE_mm_tyre003_1.geometry} material={materials.Vehicle_Exterior_mm_tyre} />
        <mesh geometry={nodes.LOD_A_TYRE_mm_tyre003_2.geometry} material={materials.Vehicle_Exterior_mm_rotor} />
        <mesh geometry={nodes.LOD_A_TYRE_mm_tyre003_3.geometry} material={materials.Vehicle_Exterior_mm_misc} />
        <mesh geometry={nodes.LOD_A_TYRE_mm_tyre003_4.geometry} material={materials.Vehicle_Exterior_mm_wheel} />
      </group>
      <group position={[-0.956, 0.331, -1.435]} rotation={[Math.PI / 2, 0, 0]} scale={[-1.101, 1.101, 1.101]}>
        <mesh geometry={nodes.LOD_A_TYRE_mm_tyre002_1.geometry} material={materials.Vehicle_Exterior_mm_tyre} />
        <mesh geometry={nodes.LOD_A_TYRE_mm_tyre002_2.geometry} material={materials.Vehicle_Exterior_mm_rotor} />
        <mesh geometry={nodes.LOD_A_TYRE_mm_tyre002_3.geometry} material={materials.Vehicle_Exterior_mm_misc} />
        <mesh geometry={nodes.LOD_A_TYRE_mm_tyre002_4.geometry} material={materials.Vehicle_Exterior_mm_wheel} />
      </group>
      <group position={[0.956, 0.331, -1.435]} rotation={[Math.PI / 2, 0, 0]} scale={1.101}>
        <mesh geometry={nodes.LOD_A_TYRE_mm_tyre001_1.geometry} material={materials.Vehicle_Exterior_mm_tyre} />
        <mesh geometry={nodes.LOD_A_TYRE_mm_tyre001_2.geometry} material={materials.Vehicle_Exterior_mm_rotor} />
        <mesh geometry={nodes.LOD_A_TYRE_mm_tyre001_3.geometry} material={materials.Vehicle_Exterior_mm_misc} />
        <mesh geometry={nodes.LOD_A_TYRE_mm_tyre001_4.geometry} material={materials.Vehicle_Exterior_mm_wheel} />
      </group>
      <mesh geometry={nodes.LOD_A_BRAKES_BOOT_mm_lights.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_BRAKES_RIGHT_mm_lights.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_HEADLIGHT_LENS_RIGHT_mm_windows.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_EXHAUST_mm_ext.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_CHASSIS_mm_misc.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_BOOT_mm_badges.geometry} material={materials.Vehicle_Exterior_mm_badges} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_BODY_mm_badges.geometry} material={materials.Vehicle_Exterior_mm_badges} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_MIRROR_RIGHT_mm_misc.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_DOOR_RIGHT_mm_misc.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_MIRROR_LEFT_mm_ext.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_BODY_mm_lights.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_HOOD_mm_misc.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_FRONTBUMPER_mm_ext.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_GLASS_LEFT_QUARTER_mm_windows.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_DOOR_RIGHT_mm_badges.geometry} material={materials.Vehicle_Exterior_mm_badges} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_DOOR_LEFT_mm_ext.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_CHASSIS_mm_chassis.geometry} material={materials.Vehicle_Exterior_mm_chassis} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_MIRROR_RIGHT_mm_ext.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_DOOR_LEFT_mm_badges.geometry} material={materials.Vehicle_Exterior_mm_badges} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_BRAKES_LEFT_mm_lights.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_CHASSIS_mm_lights.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_DOOR_LEFT_mm_cab.geometry} material={materials.Vehicle_Exterior_mm_cab} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_REARBUMPER_mm_misc.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_BOOT_mm_ext.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_HOOD_mm_badges.geometry} material={materials.Vehicle_Exterior_mm_badges} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_BODY_mm_misc.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_BOOT_mm_misc.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_MIRROR_GLASS_RIGHT_mm_misc.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_GLASS_FRONT_mm_windows.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[0.956, 0.313, 1.161]} rotation={[Math.PI / 2, 0, 0]} scale={1.04}>
        <mesh geometry={nodes.LOD_A_TYRE_mm_tyre_1.geometry} material={materials.Vehicle_Exterior_mm_tyre} />
        <mesh geometry={nodes.LOD_A_TYRE_mm_tyre_2.geometry} material={materials.Vehicle_Exterior_mm_rotor} />
        <mesh geometry={nodes.LOD_A_TYRE_mm_tyre_3.geometry} material={materials.Vehicle_Exterior_mm_misc} />
        <mesh geometry={nodes.LOD_A_TYRE_mm_tyre_4.geometry} material={materials.Vehicle_Exterior_mm_wheel} />
      </group>
      <mesh geometry={nodes.LOD_A_MIRROR_LEFT_mm_misc.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_STEERING_WHEEL_mm_cab.geometry} material={materials.Vehicle_Exterior_mm_cab} position={[0.361, 0.691, 0.36]} rotation={[1.884, 0, 0]} />
      <mesh geometry={nodes.LOD_A_FRONTBUMPER_mm_misc.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_MIRROR_GLASS_LEFT_mm_misc.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_TAILLIGHT_LENS_LEFT_mm_lights.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_HOOD_mm_ext.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_DOOR_LEFT_mm_misc.geometry} material={materials.Vehicle_Exterior_mm_misc} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_GLASS_LEFT_mm_windows.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_GLASS_mm_windows.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_BODY_mm_ext.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_GLASS_RIGHT_QUARTER_mm_windows.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_BOOT_mm_lights.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_HEADLIGHT_LENS_LEFT_mm_windows.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_DOOR_RIGHT_mm_ext.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_GLASS_RIGHT_mm_windows.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_TAILLIGHT_LENS_RIGHT_mm_lights.geometry} material={materials.Vehicle_Exterior_mm_lights} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_INTERIOR_mm_cab.geometry} material={materials.Vehicle_Exterior_mm_cab} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_REARBUMPER_mm_ext.geometry} material={materials.Vehicle_Exterior_mm_ext} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_DOOR_RIGHT_mm_cab.geometry} material={materials.Vehicle_Exterior_mm_cab} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.LOD_A_GLASS_REAR_mm_windows.geometry} material={materials.Vehicle_Exterior_mm_windows} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/ferrari.glb')
