import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";

const rajdhani = Rajdhani({

  weight:["300", "400", "500", "600", "700"],
  subsets:["latin"],
  display:"swap"

})



export const metadata: Metadata = {

  title: "FerLux Auto",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" data-theme="dark">
      <body className={`${rajdhani.className}`}>
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
