import type { Metadata } from "next";
import { Poppins} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";

const poppins = Poppins({

  weight:["100", "200", "300", "400", "500", 
    "600", "700", "800", "900"],
  subsets:["latin"],
  display:"swap"

})

export const metadata: Metadata = {

  title: "FerLux Auto",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" data-theme="dark">
      <body className={`${poppins.className}`}>
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
